edkrepo/commands/arguments/update_manifest_repo.py
edkrepo/commands/update_manifest_repo_command.py

Adds functionality to update the copy of the global
manifest repo(s) used by EdkRepo

EdkRepo: Add the update_manifest_repo command

---

edkrepo/commands/combo_command.py

print_info_msg to print the result in a standardized way.

EdkRepo: combo command to have standardized messaging

---

edkrepo/commands/cache_command.py

print_info_msg to print the result in a standardized way.

EdkRepo: cache command to have standardized messaging

---

License.txt

Add license.txt

---

edkrepo/commands/status_command.py

Standardize messaging in status command.

Standardize messaging in status command.

---

edkrepo/commands/sparse_command.py

Standardize messaging in sparse command.

Standardize messaging in sparse command.

---

edkrepo/commands/manifest_repos_command.py

Standardize messaging in manifest_repos command.

Standardize messaging in manifest_repos command.

---

edkrepo/commands/checkout_pin_command.py

Standardize messaging in checkout_pin command.

Standardize messaging in checkout_pin command.

---

edkrepo/commands/sync_command.py

Standardize messaging in sync command.

Standardize messaging in sync command.

---

edkrepo/commands/manifest_command.py

Standardize messaging in manifest command.

Standardize messaging in manifest command.

---

edkrepo/commands/arguments/list_pins_args.py
edkrepo/commands/humble/list_pins_humble.py
edkrepo/commands/list_pins_command.py

This command provides support for listing all pin files in the
global manifest repository.

EdkRepo: Add list pins command

---

edkrepo/commands/maintenance_command.py

Standardize messaging in maintenance command.

Standardize messaging in maintenance command.

---

edkrepo/commands/sync_command.py
edkrepo/common/common_repo_functions.py
edkrepo/common/workspace_maintenance/git_config_maintenance.py

Changing includeif path syntax to be up-to-date with newer versions of Git

EdkRepo: Update includeifs in .gitconfig

---

edkrepo/common/workspace_maintenance/manifest_repos_maintenance.py

Edkrepo: Add cloning of a specific branch using single_branch

---

edkrepo/commands/arguments/f2f_cherry_pick_args.py

Signed-off-by: Harsh Vora harsh.vora@intel.com
Solves issue #69

Edkrepo: Removed the unicode character \u200b.

---

Maintainers.txt

Adding myself as a reviewer, and removing Puja Pandya as she is no longer working on this project.

EdkRepo: Editing Maintainers.txt file

---

edkrepo/common/common_repo_functions.py

Update the checkout() method to recompute the sparse checkout state
if two combos have different statically defined sparse checkout lists.
Resolves #80

EdkRepo: Recompute sparse checkout state when running checkout <combo>

---

edkrepo/common/workspace_maintenance/manifest_repos_maintenance.py

If global manifest repo has a redirect, EdkRepo will always think it was moved. Aim to remove this behavior by recognizing redirects as not moving.

EdkRepo: Recognize if global manifest is redirected

---

edkrepo/commands/arguments/clean_args.py
edkrepo/commands/clean_command.py

resolves #125
Signed-off-by: Megan Chauhan <megan.chauhan@intel.com>

EdkRepo: implement edkrepo clean -x

---

edkrepo/commands/cache_command.py
edkrepo/common/common_repo_functions.py
project_utils/cache.py

Includes new behavior to pass through a git lfs fetch --recent in the event that no new LFS objects were updated recently

EdkRepo: Various fixes for selective cache update

---

edkrepo/commands/humble/sync_humble.py
edkrepo/commands/sync_command.py
edkrepo/common/humble.py

EdkRepo: Move sync specific strings to a sync specific location

---

edkrepo/commands/sync_command.py

EdkRepo: Fix sync humble import

---

edkrepo/commands/checkout_pin_command.py

Add the global_manifest_path parameter to the
checkout_repos() call.
Corrects issue with pin resolution by
ensuring .xml is appended to args.pinfile if only
a name is used.
Additionally refactor the logic of __get_pin_path() so that it is easier to follow.
Fixes #142
Fixes #145

EdkRepo: Fix Checkout Pin

---

edkrepo_manifest_parser/edk_manifest.py

EdkRepo: add patchset to pinfile

---

edkrepo/commands/f2f_cherry_pick_command.py

Function argument was erroneously changed in previous commit

EdkRepo: Fix bug in f2f

---

edkrepo/common/common_repo_functions.py

If a revert fails, check for unmerged changes and abort the revert.  
If a cherry-pick fails, check for unmerged changes and abort the cherry-pick.  
Unmerged changes left on the dynamic branch creation branch will prevent edkrepo from checking out the default branch and deleting the incomplete dynamic branch creation branch as part of the first step of the exception handling recovery.
After deleting the unsuccessful dynamic branch creation git branch, re-raise the exception to attempt to checkout the previously known good combo.
Issue:  
https://github.com/tianocore/edk2-edkrepo/issues/154

Improve error recovery from a corrupt PatchSet recipe.

---

edkrepo/commands/list_repos_command.py

The list repos command will fail to process if any of the available manifest files contain a combo which does not reference a branch. Update the command to by-pass this case and to identify if a commit or a tag is used in a combo. The output has been updated to show all branches, commits or tags in a given repo that are used and which combo they are used in.
Fixes: #167

EdkRepo: List Repos Should Handle Combos That Do Not Reference a Branch

---

edkrepo/commands/cache_command.py

Check for args.project before attempting to determine if it's pointing to a file

EdkRepo: Do not attempt to resolve None as path

---

edkrepo/common/common_repo_functions.py

The global manifest directory for all repositories in a single workspace is the same. This value should be calculated once per clone_repos() call not once per repo cloned.

EdkRepo: Only calculate global_manifest_repo once during clone_repos

---

edkrepo/common/clone_utilities.py
edkrepo/common/common_repo_functions.py

Move clone_single_repository() to common_repo_functions.py to resolve circular dependency.

EdkRepo: Resolve circular dependency.

---

build-scripts/build_windows_installer.bat
edkrepo_installer/EdkRepoInstaller/EdkRepoInstaller.csproj
edkrepo_installer/EdkRepoInstaller/app.config

Fix VS2022 bugs in build_windows_installer.bat

Update Target .NET Framework to 4.6

---

edkrepo_installer/linux-scripts/install.py

Debian 12 and later does not allow normal pip behavior outside of a venv unless the --break-system-packages flag is given.

Fix installation failures on Debian 12+

---

project_utils/submodule.py

https://github.com/tianocore/edk2-edkrepo/issues/255

Update submodule when no partialclonefilter is set in repo.

---

edkrepo_installer/EdkRepoInstaller/InstallWorker.cs

REF: https://github.com/tianocore/edk2-edkrepo/issues/261
The EdkRepo installer does a check to make sure that the Windows directory is contained within the PATH environment variable. However, retrieving the current value of PATH is done via a string comparison with "Path". Since environment variables are case-insensitive on Windows, the environment variable could be named "Path", "path", or "PATH". If "Path" is not found, then EdkRepo will clear and overwrite the current value of the PATH environment variable at a system level. The fix for this issue is to perform a case-insensitive comparison when searching for the PATH environment variable.

EdkRepo: Installer should perform a case-insensitive compare for PATH

---

edkrepo_manifest_parser/edk_manifest.py

Resolve failure to create Pin files due to extra _ in self._combinations

EdkRepo: Fix Pin Creation

---

edkrepo_manifest_parser/edk_manifest.py

Adding SparseSettings to pin files to define cloning behavior

EdkRepo: Include SparseSettings in Pin Files

---

edkrepo/commands/combo_command.py
edkrepo/commands/humble/common_humble.py
edkrepo/commands/manifest_command.py
edkrepo/common/workspace_maintenance/manifest_repos_maintenance.py

When using the -v flag display informative information about the manifest repository that the project is listed in.

EdkRepo: Add manifest repo information to combo command.
