tianocore/edk2-edkrepo

- edkrepo/commands/cache_command.py
Edkrepo cache command is updated to clone/sync all the global manifests defined in the edkrepo_cfg and the edkrepo_user.cfg
Cc: Ashley E Desimone <ashley.e.desimone@intel.com>
Cc: Nate DeSimone <nathaniel.l.desimone@intel.com>
Cc: Puja Pandya <puja.pandya@intel.com>
Cc: Bret Barkelew <Bret.Barkelew@microsoft.com>
Cc: Erik Bjorge <erik.c.bjorge@intel.com>
Signed-off-by: Moonjung Kyung <moonjung.kyung@intel.com>
> EdkRepo: Edkrepo cache doesn't download manifest files

- edkrepo/commands/sync_command.py
This resolves the "error: cannot lock ref 'refs/y': 'refs/x' exists;
cannot create 'refs/y'" message that is seen when a individual ref
is changed to a folder of refs. When this unusual even occurs, a
prune of existing refs needs to be done. It would be useful if
EdkRepo is able to detect this exceptional case and perform the prune
automatically.
> EdkRepo: Automatic remote prune in EdkRepo Sync

- edkrepo_installer/Vendor/edkrepo.cfg
Use the newly created edk2-edkrepo-manifest repository for the
global manifest repository instead of the one in Edk2-staging
> EdkRepo - Update the edkrepo.cfg

- edkrepo/commands/arguments/reset_args.py
- edkrepo/commands/reset_command.py
The reset command provides the same functionality
as running git reset on all repositories in the
workspace.
> EdkRepo: Add the reset command

- edkrepo/commands/arguments/clean_args.py
- edkrepo/commands/clean_command.py
The clean command adds functionality equivalent of
running git clean on all repositories in the workspace.
> EdkRepo: Add the Clean command

- edkrepo/commands/arguments/status_args.py
- edkrepo/commands/humble/status_humble.py
- edkrepo/commands/status_command.py
Provides functionality equivalent to running git
status for all repositories in the workspace.
Additionally displays the currently checked out
combo
> EdkRepo: Add the status command

- edkrepo/common/common_repo_functions.py
EdkRepo clone fails if the manifest file specified does not
exist in any of the the global manifest repositories.
> EdkRepo: Clone fails if the manifest is not in CiIndex.xml

- edkrepo_installer/Vendor/edkrepo.cfg
Rename edk2-staging to edk2-edkrepo-manifest in
edkrepo.cfg to accurately reflect the new name
of the manifest repo.
> EdkRepo: Rename edk2-staging to edk2-edkrepo-manifest

- edkrepo/commands/arguments/log_args.py
- edkrepo/commands/log_command.py
- edkrepo/common/common_repo_functions.py
- edkrepo/common/ui_functions.py
Add the log command which generates an interleaved log
of all repositories in the workspace allowing the user to view
a single unified history of the project.
> EdkRepo: Add the log command

- build-scripts/cln.bat
'edkrepo*.tar.gz' pattern added to files to delete in cln.bat to remove all build artifacts.
> 'edkrepo*.tar.gz' pattern added to cln.bat to remove all build artifacts.

- edkrepo/commands/clean_command.py
print_info_msg to print the result in a standardized way.
> EdkRepo: clean command to have standardized messaging

- edkrepo/commands/f2f_cherry_pick_command.py
In the case of f2f-cherry-pick needs to perform more than one
cherry-pick operation to complete the f2f-cherry-pick, the
final action edkrepo will perform is squashing the several
cherry-picks down to one commit. This squash will erroneously
drop the top commit on the target branch before performing
the final cherry-pick.
> EdkRepo: f2f-cherry-pick will drop the top commit in some cases

- edkrepo/commands/reset_command.py
print statements use standardized formatting.
> EdkRepo: reset command to have standardized messaging

- edkrepo/commands/checkout_pin_command.py
- edkrepo/commands/clone_command.py
- edkrepo/commands/create_pin_command.py
- edkrepo/commands/sync_command.py
- edkrepo/common/common_repo_functions.py
- edkrepo/common/workspace_maintenance/manifest_repos_maintenance.py
If the project for a manifest file moves from one manifest repository to
another, then it is possible for the SourceManifestRepository under
GeneralConfig to refer to a manifest repository that no longer exists or
does not contain a project with the same codename.
This patch adds detection for this scenario. If it occurs, then a full
search of all known manifest repositories is conducted to attempt to
find the new location of the project's manifest. If the new manifest
directory is found, then the SourceManifestRepository is updated to
point to the new manifest repository.
In some scenarios, "edkrepo sync -uo" will need to clone a new git repository.
Specifically, if the new version of the project's manifest file adds a git
repository that did not exist before. In that scenario, updating …
> Handle broken source manifest repo links and sync modifies the global manifest repo if it needs to clone a new repo

- edkrepo/common/common_repo_functions.py
Detect the path to curl for use in GitHub API calls.
> EdkRepo: Detect curl path

- edkrepo/commands/create_pin_command.py
Standardize messaging in create_pin command.
> Standardize messaging in create_pin command.

- edkrepo_installer/EdkRepoInstaller/InstallWorker.cs
Support the use of Git LFS by adding a call to git lfs install
to the EdkRepo installer.
> EdkRepo: Add LFS installation

- edkrepo/commands/arguments/create_pin_args.py
- edkrepo/commands/create_pin_command.py
- edkrepo/common/humble.py
Direct push functionality is not supported by most
access controlled git environments and oftentimes creates
non-linear histories when not desired. As such remove the
direct push functionality until there is a defined requirement
or use case which warrants it.
> EdkRepo: Deprecate create-pin --push

- edkrepo_installer/EdkRepoInstaller/InstallWorker.cs
The Python launchers installed by EdkRepo should explicitly point
to the supported version where possible allowing and git hooks to
'import edkrepo' if needed.
> EdkRepo: Specify the Python version in installed Python launcher

- edkrepo_installer/linux-scripts/install.py
Installation of EdkRepo will currently fail on Linux or macOS if the user's
home directory does not contain either a .bashrc or a .zshrc file.
Adjusted conditional logic to handle this case correctly.
> EdkRepo: Install Fails if .bashrc/.zshrc Doesn't Exist

- edkrepo_installer/mac-scripts/setup_git_pyenv_mac.sh
New versions of pyenv require a call to pyenv init --path
Add a call to this command.
> EdkRepo: Enable new version of pyenv

- edkrepo/common/common_repo_functions.py
- edkrepo/common/humble.py
If the location of the global manifest repository changes, then the
commit.template git config settings added by EdkRepo will point to
commit templates that no longer exist. During sync, we should detect
if the commit template file no longer exists and update it to the new
commit template location.
Cc: Ashley E Desimone <ashley.e.desimone@intel.com>
> 'git commit' fails with could not read '': No such file or directory

- edkrepo/commands/sync_command.py
edkrepo sync fails if run on a new system that does not have the
global manifest repository cloned yet.
- The manifest repository needs to be pulled before
find_source_manifest_repo() is called since that function needs to
access the manifest repo. Reordered these function calls.
- Added call to pull_all_manifest_repos() if there is an error pulling
the source manifest repo. This will cover the case of the source
manifest repo not existing.
> edkrepo sync fails if the global manifest repository does not exist

- edkrepo/commands/maintenance_command.py
4381e98 adds an extra closing parenthesis in
maintenance_command.py which causes a syntax error.
Removing this extraneous character.
Cc: Ashley E Desimone <ashley.e.desimone@intel.com>
> EdkRepo: Fix syntax error in maintenance_command.py

- edkrepo/commands/combo_command.py
- edkrepo/commands/composite_command.py
- edkrepo/commands/f2f_cherry_pick_command.py
- edkrepo/commands/list_repos_command.py
- edkrepo/commands/log_command.py
- edkrepo/commands/manifest_command.py
- edkrepo/common/ui_functions.py
Refactoring to allow messaging framework to be accessible in all commands through inheritance, rather than in a select few commands. Also avoids known colorama behavior that would cause an exponential amount of recursive exceptions.
Signed-off-by: Kevin Sun [kevinsun@intel.com](mailto:kevin.sun@intel.com)
> EdkRepo: Updating messaging framework to be more consistent

- edkrepo/common/edkrepo_exception.py
Updates error codes in edkrepo_exception.py to consecutive order starting at 100x.
Resolves issue #84 
Signed-off-by: Shreeshan Panicker shreeshan.p@yahoo.com
Reviewed-by: Nate DeSimone nathaniel.l.desimone@intel.com
Reviewed-by: Ashley DeSimone ashley.e.desimone@intel.com
> EdkRepo: Update Error Codes in edkrepo_exception.py

- edkrepo_manifest_parser/edk_manifest.py
CombinationList is not required but not prohibited in a pin file.
Account for its present when identifiying the number of combos in
a pin file.
Signed-off-by: Yuwei Chen <yuwei1.chen@intel.com>
Co-authored-by: Yuwei Chen <yuwei1.chen@intel.com>
> EdkRepo: Account for CombinationList being present in a pin file

- edkrepo_manifest_parser/edk_manifest.py
Add support for additional meta data required by EdkRepo to
create Python virtual environemtns on a per combo basis.
resolves issue #58
> EdkRepo: Add support for Python Virtual Environments

- Maintainers.txt
Add Kevin Sun as a maintainer.
Update urls to point from edk2-staging to edk2-edkrepo
> EdkRepo: Update Restricted Maintainers FIle

- edkrepo/config/config_factory.py
In the definition of BaseConfig an extra '.' was
present in the definition of the CfgProp.name entry for URL and LocalPath.
> EdkRepo: Remove '.' from CfgProp Definitions

- edkrepo/commands/sync_command.py
- edkrepo/common/common_repo_functions.py
Remove the stub implementations and uses of the
following functions:
in_sync_with_primary()
fetch_from_primary_repo()
add_primary_repo_remote()
has_primary_repo_remote()
> EdkRepo: Remove Unimplemented Functions

- edkrepo/commands/clone_command.py
- edkrepo_manifest_parser/edk_manifest.py
Adds option to generate pin files in JSON format, as well as option to clone from a JSON pin file. Notably will skip validation if JSON file is given as input.
> EdkRepo: Adding support for cloning and generating JSON pin files

- edkrepo/commands/sync_command.py
- edkrepo/common/common_repo_functions.py
- edkrepo/common/git_version.py
- edkrepo/common/workspace_maintenance/git_config_maintenance.py
Includeif updates consist of adding "%(prefix)" to all includeif entries in .gitconfig file but caused some regressions. Updating to make this update Git-version-specific as the update is only needed for Git versions 2.34.0 and higher.
> EdkRepo: Version-specific includeifs in .gitconfig

- edkrepo/commands/sync_command.py
ConfigParser does not support overwriting a gitconfig entry so we are manually deleting it if it exists to write over it.
> EdkRepo: Further sync fixes

- edkrepo/common/workspace_maintenance/git_config_maintenance.py
Only the project-specific gitconfig file will inform whether the includeif entry should be deleted. All other checks are not necessary
> EdkRepo: Simplifying gitconfig cleanup logic

- edkrepo/commands/sync_command.py
patchset_branch_creation_flow call missing argument during sync command. When using manifests with PatchSet implemented, sync command may fail.
> Edkrepo: sync command fails with PatchSet manifest

- edkrepo/common/common_repo_functions.py
Issue:
When using a manifest with PatchSet implemented, json files are created to track edkrepo PatchSet branch information. If edkrepo has not created any PatchSet branches yet, there is no json file created. If edkrepo detects a branch name collision with a local user branch before creating a json file, edkrepo command will fail.
Solution:
When a branch name collision is detected, check for the json file before attempting to open the json file. When no json file exists yet, treat the branch name collision as a user-made local branch collision. Notify user with an error message, then attempt to revert to previous combo.
> Edkrepo: file access failure during branch name conflict

- edkrepo/commands/sync_command.py
- edkrepo/common/humble.py
REF: https://github.com/tianocore/edk2-edkrepo/issues/110
Add an additional heuristic that triggers the automatic remote prune. This should catch more cases of this issue.
Signed-off-by: Nate Desimone <nathaniel.l.desimone@intel.com>
> EdkRepo: Improve automatic remote prune in EdkRepo Sync

- README.md
- edkrepo/commands/command_factory.py
https://github.com/tianocore/edk2-edkrepo/issues/120 
Replace deprecated inspect.getargspec with inspect.getfullargspec
> Edkrepo fails to install with Python3.11

- edkrepo/commands/arguments/cache_args.py
- edkrepo/commands/cache_command.py
Gate all update operations behind not args.info
Enable --update to turn on caching.
> EdkRepo: Cache Improvements

- edkrepo/common/common_repo_functions.py
https://github.com/tianocore/edk2-edkrepo/issues/123
When determining branch collision, the patchset parent_sha value should not match the branch name. If the patchset parent_sha value matches the branch name, continue testing the remaining patchsets.
> dynamic branch json file corruption during edkrepo sync

- edkrepo/commands/sync_command.py
In the sync -u flow only the repository defining characteristics of a repo_source tuple should be used to determine whether the initial and new source are the same. This change ensures that only the remote name, url and local root are compared.
Fixes #135
> EdkRepo: Fix incorrect manifest change calculations

- edkrepo/common/common_repo_functions.py
- edkrepo_manifest_parser/edk_manifest.py
Currently, two PatchSet can be chained together to create a dynamic branch.
If a third or more PatchSet is chained in a row, these PatchSet fail to create a dynamic branch when used, and non-gracefully fails when the PatchSet steps are attempted on the wrong branch or commit.
Locate the correct base PatchSet from the manifest before attempting to create the branch. If a PatchSet circular dependency is found, raise an exception. Do not attempt to create the branch if any exception besides KeyError is encountered.
> Daisy-chaining PatchSet fails to create branch

- edkrepo/commands/checkout_pin_command.py
- edkrepo/commands/humble/checkout_pin_humble.py
- edkrepo/commands/humble/sync_humble.py
- edkrepo/commands/sync_command.py
- edkrepo/common/humble.py
With the refactor and use of ui_functions to print some strings, we need to audit their use of the headers parameter and remove explicit use of "warning", "error", etc. from humble files
> EdkRepo: Audit strings

- edkrepo/commands/list_pins_command.py
When use_less == true std_out was redirected to capture manifest parser output but never reset preventing subsequent print operations from being visible on the console.
Additionally switch from using subprocess.communitcate() to subprocess.run() to eliminate the stack trace reported in #148
Fixes #148
> EdkRepo: Fix stack trace in List Pins

- edkrepo_manifest_parser/edk_manifest.py
The addition of patchset support for pin files causes an error if a patchset is not present in the parent manifest file.
> EdkRepo: Generate PinFile w/o patchsets

- README.md
- edkrepo_installer/linux-scripts/install.py
REF: #163
- If bash-completion is available then it will now be used on Linux systems. This resolves an issue on Raspberry Pi OS where installing EdkRepo will cause the X11 server to crash during startup. The reason this occurs is because the X11 startup scripts on Raspberry Pi blindly runs all scripts in /etc/profile.d using /bin/sh
- Adds support for user local installs on Linux and makes that the recommended method.
- Adds interactive installation mode to aid users in setting the installation options correctly.
- Fixes shell integration on Raspberry Pi OS.
- Some of the shell initialization script additions made by the installer are typically only needed on macOS. Moved those to only be added if the current OS is macOS.
- Update README.md to document the new Linux installation script …
> EdkRepo Linux Installer Improvements

- edkrepo/commands/sync_command.py
Currently all errors from the __update_local_manifest() method in the sync command are only visible when using the -v flag. This prevents users from knowing why the manifest update was not completed succesfully and that in many cases it can be re-run and complete if the -o flag is used.
Fixes #166
> EdkRepo: Unmask errors from __update_local_manifest() method.

- edkrepo/commands/combo_command.py
When a commit or tag are referenced in a combo list them in the output of combo -v like branch names or patchsets.
> EdkRepo: Add Tags and Commits to Combo -V output

- edkrepo_installer/EdkRepoInstaller/InstallWorker.cs
During the Windows installation process run:
"git config --global core.longpaths true"
Fixes #177
> EdkRepo Installer: Configure core.longpaths support

- edkrepo/commands/cache_command.py
When passing in a pin or manifest file and the --selective flag is use skip the update of all manifest repositories.
Fixes #179
> EdkRepo: Improve performance of cache command

- project_utils/cache.py
When the default remote name 'origin' is used for a cached repository the cache's directory name will be the repository name not the remote name; when this occurs the url_or_name parameter will match the value of remote.name. This commit updates the conditional in update_cache() to handle this case by checking for both possibilities.
Fixes #184
> Selective Caching Does Not Function When Default Remote Name is Used

- edkrepo/commands/combo_command.py
- edkrepo/commands/list_repos_command.py
In the List-Repos command a combo referencing a combination of tag, sha, and branch would only have the branch listed. Update if / elif block to ensure that all ref types are listed
In the combo commmand a combo containing a combination of tag, sha and branch would only show the branch. Update the conditionals such that the printed ref follows EdkRepo's priority order of ref usage (SHA > Tag > Branch)
Fixes #182
> EdkRepo: Process Refs By Priority Order in List-Repos and Combo

- edkrepo_installer/EdkRepoInstaller/InstallWorker.cs
REF: https://github.com/tianocore/edk2-edkrepo/issues/189
If the DWORD FIPSAlgorithmPolicy under
HKLM\System\CurrentControlSet\Control\Lsa
is set to 1, then the edkrepo installer fails because it is using a SHA256 implementation that was not certified for FIPS. The fix is to switch from SHA256Managed to
SHA256CryptoServiceProvider.
> EdkRepo: Use FIPs Certified SHA256 Implementation

- edkrepo/commands/arguments/maintenance_args.py
- edkrepo/commands/maintenance_command.py
Add the --no-gc flag to enable the user to skip garbage collection operations while performing other maintenance operations.
Fixes #196
> EdkRepo: Add option to skip garbage collection during maintenance

- edkrepo_installer/linux-scripts/install.py
REF: #198
If the linux installer is passed the --system or --local flags then it will attempt to do the opposite of what the user requests.
If the user installs in interactive mode, then this issue is not seen.
> EdkRepo: install.py uses wrong installation mode

- edkrepo/common/edkrepo_exception.py
> Fixing typo in error init function

- edkrepo/commands/arguments/cache_args.py
- edkrepo/commands/cache_command.py
When running cache commands with a custom path defined the default path will be restored. This was due to the handling of cache commands when the --path flag was not specified.
Updated the --path flag handling logic to do noting if not present. The default path can be restored by passing 'default' as the PATH parameter.
> Fixing default cache path restoration issue

- edkrepo/commands/f2f_cherry_pick_command.py
In git version 2.39 and newer, the text indicating a cherry-pick merge conflict changed from:
"after resolving the conflicts"
to:
"After resolving the conflicts"
Changed the string comparison to be case insensitive.
> Fix f2f-cherry-pick failure when merge conflicts occur

- edkrepo_installer/linux-scripts/install.py
If one of the req_tools entries in the install.cfg file does not exist on the system, then the EdkRepo installer should fail before making any changes to the system.
> EdkRepo Linux/Mac installer should fail if a pre-req is missing.

- edkrepo/common/clone_utilities.py
- edkrepo/common/common_repo_functions.py
Introduces the file clone_utilities.py and the methods:
- generate_clone_command(): Which generates a string representing a git clone command to be used by subprocess based on command line arguments, manifest file contents and cache status
- clone_single_repository(): Which clones a single repository and checks out the ref specified in the project manifest file.
Updates the clone_repos() method in common_repo_functions.py to leverage the new clone_single_repository() method.
Fixes: #221
> EdkRepo: Implement a method to clone a single repository

- edkrepo/common/clone_utilities.py
Change an elif to an if to ensure that both the -b <branch> flag and any command line flags are added to the generated git command.
Co-authored-by:Zhen Gong <zhen.gong@intel.com>
> EdkRepo: Address logical error in generate_clone_cmd

- edkrepo/common/clone_utilities.py
The argpasrse namespace throws Attribute Errors instead of KeyError this commit updates generate_clone_cmd to take that into account.
> EdkRepo: Change KeyError to AttribueError

- edkrepo_manifest_parser/edk_manifest.py
Currently takes the CurrentClonedCombo from the manifest file the pin is based off of. But it should be also setting it to the combo passed into the method, as that's the only <Combination> that will be present in the resulting pin file.
> EdkRepo: generate_pin_etree should also set CurrentClonedCombo

- edkrepo/edkrepo_cli.py
- edkrepo/edkrepo_entry_point.py
Use of pkg_resources is deprecated in favor of importlib.metadata 
https://github.com/tianocore/edk2-edkrepo/issues/211
> Remove pkg_resources for Python 3.12 support

- edkrepo/common/pathfix.py
- edkrepo/edkrepo_cli.py
Per the README.md file, retain Python 3.5 support for Linux.
> Support running edkrepo_cli with Python 3.5

- edkrepo/commands/combo_command.py
When current combo is not in the combo_list, update both combo_list and all_combos.
verbose combo error while archived combo is checked out https://github.com/tianocore/edk2-edkrepo/issues/231
> combo command verbose current combo fix.

- project_utils/submodule.py
When no selective submodule initialization is present recursive initialization should be completed.
> EdkRepo: Ensure that recursive submodule init is completed.

- edkrepo/commands/arguments/clone_args.py
- edkrepo/commands/clone_command.py
- edkrepo/common/clone_utilities.py
- edkrepo/common/humble.py
- edkrepo_manifest_parser/edk_manifest.py
- project_utils/submodule.py
Adds treeless="true" and blobless="true" as attributes to a Combination Source. 
During edkrepo clone and checkout, if enableSubmodule="true" on the Combination Source, the filter setting applies to the submodules as well.
--treeless and treeless="true" have priority over --blobless and blobless="true" if multiple are used.
During edkrepo clone, --treeless and --blobless do not apply to the submodule filter settings.
Related issues:
https://github.com/tianocore/edk2-edkrepo/issues/239  
add filter configurations at a per-Source or per-Remote granularity
https://github.com/tianocore/edk2-edkrepo/issues/247  
clone with both --treeless and --blobless encounter git error
> Add filter configurations at a per-Source granularity

- edkrepo/commands/clean_command.py
- edkrepo/commands/command_factory.py
- edkrepo/commands/f2f_cherry_pick_command.py
- edkrepo/commands/list_repos_command.py
- edkrepo/commands/log_command.py
- edkrepo/commands/maintenance_command.py
- edkrepo/commands/reset_command.py
- edkrepo/common/git_version.py
- edkrepo/common/ui_functions.py
- edkrepo/git_automation/commit_msg.py
- edkrepo/git_automation/rebase_squash.py
Edkrepo scripts must follow the PEP 8 Style Guide for Python code. This change organizes the import statements for edkrepo scripts into three blocks:
- Standard Python imports
- Third-party imports
- Edkrepo imports
> EdkRepo: Organize import statements

- edkrepo/commands/sync_command.py
- edkrepo/common/workspace_maintenance/git_config_maintenance.py
To resolve "SyntaxWarning: invalid escape sequence '\('" with Python 3.12.4. https://github.com/tianocore/edk2-edkrepo/issues/251
Test system: git version 2.43.0.windows.1 , Python 3.5.4 / Python 3.12.4, 
Tested "edkrepo sync -u" command with Python 3.5.4 and Python 3.12.4 on Windows, and both located the new regex expression during sync.
Tested "edkrepo maintenance" command with Python 3.5.4 and Python 3.12.4 on Windows, and both located the new regex expression during maintenance.
SyntaxWarning messages not seen when running with python 3.12.4.
Did not test on non-Windows systems.
> SyntaxWarning on three regex expressions.

- edkrepo/commands/humble/manifest_humble.py
- edkrepo/commands/manifest_command.py
- edkrepo_manifest_parser/edk_manifest.py
- edkrepo_manifest_parser/edk_manifest_validation.py
Improve the output and readability of the
manifest command.
Adds a list of combos to the verbose output.
Removes print from manifest parser.
Fixes #205
> EdkRepo: Add Combo Details to Manifest -v

- edkrepo/commands/combo_command.py
When a Pin file is checked out the value of the current cloned combo is a custom string that indicates a pin file is in use; however, a combo with this name is not present in the workspace's local manifest file resulting in an error when accessing the combo's description.
In this case the error can be avoided by setting the value of the description to None.
> EdkRepo: Fix Combo Verbose Output When a Pin File is Checked Out

- edkrepo/commands/combo_command.py
- edkrepo/commands/humble/combo_humble.py
When checked out onto a pin file the combo details are not present in the local manifest file. In this case use a message should be displayed indicating that the that the currently checked out references are being shown and git status should be used to determine those references.
> EdkRepo: Enhance verbose combo output.

- edkrepo/config/config_factory.py
The geo mirror feature has been removed from EdkRepo. This commit removes the last config properties for this feature.
> EdkRepo: Remove unused properties from config
